sudo: false # to use faster container based build environment
language: elixir
elixir:
  - 1.5.3
  - 1.6
  - 1.7
otp_release:
  - 18.3
  - 19.3
  - 20.0
  - 21.0
script:
  - "MIX_ENV=test mix do deps.get, test"
